# Generated by Django 4.1.5 on 2023-01-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=100)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In process'), ('SC', 'Success'), ('FD', 'Failed')], default='IP', max_length=2)),
                ('user_email', models.EmailField(max_length=200)),
                ('delivery_address', models.CharField(max_length=300)),
                ('order_id_in_shop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book_store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_item_id', models.ManyToManyField(to='warehouse_app.bookitem')),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.orderitem')),
            ],
        ),
    ]
